<hr />

<h2>Heading H2</h2>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<h3>Heading H3</h3>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<blockquote>
	This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote. This is an exmple Blockquote.
</blockquote>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<ul>
	<li>My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. </li>
	<li>My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. My list item. </li>
</ul>

<form>
	<p>
		<label for="example-input">Input Field Label:</label><input id="example-input" type="text" value="" placeholder="Placeholder">
	</p>
	<p>
		<label for="example-select">Select Field Label:</label>
		<select id="example-select" >
			<option value="Option 1">Option 1</option>
			<option value="Option 2">Option 2</option>
			<option value="Option 3">Option 3</option>
		</select>
	</p>
	<p>
		<label for="example-textarea">Textarea Label:</label>
		<textarea name="nachricht" cols="40" rows="4"></textarea></span></p>
	<p>
	<p>
		<label for="submit">&nbsp;</label>
		<input value="Submit"  type="submit">
	</p>
</form>
<hr />

<h3>Grid Example</h3>

<p>Use the grid via .row and .col mixins or as HTML classes in the Markup.</p>

<div class="debug-grid">
	<div class="row">
		<div class="col-6">
			<div class="row">
				<div class="col-3 push-3"></div>
				<div class="col-3"></div>
				<div class="col-3 pull-9"></div>
			</div>
		</div>
		<div class="col-6">
			<div class="row">
				<div class="col-4 push-4"></div>
				<div class="col-4 pull-8"></div>
			</div>
		</div>
	</div>
</div>

<hr />

<h3>Helper</h3>

<h4>Display Table</h4>

<div class="helper-display-table">
	<div>
		Cell Left<br/>
		with more than<br/>
		one line!
	</div>
	<div>
		Cell Right
	</div>
</div>
