<h2>Heading H2</h2>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<h4>Grid Example</h4>

<p>Use the grid via .row and .col mixins or as HTML classes in the Markup.</p>

<div class="debug-grid">
	<div class="row">
		<div class="col-6">
			<div class="row">
				<div class="col-3"></div>
				<div class="col-3"></div>
				<div class="col-3"></div>
				<div class="col-3"></div>
			</div>
		</div>
		<div class="col-6">
			<div class="row">
				<div class="col-4"></div>
				<div class="col-4"></div>
				<div class="col-4"></div>
			</div>
		</div>
	</div>
</div>