<h2>Heading H2</h2>

<p>A paragraph with a <a href="#">Link</a> and some more text. A paragraph with a <a href="#">Link</a> and
	some more text.</p>

<h3>Grid Example</h3>

<p>Use the grid via .row and .col mixins or as HTML classes in the Markup.</p>

<div class="debug-grid">
	<div class="row">
		<div class="col-6">
			<div class="row">
				<div class="col-3 push-3"></div>
				<div class="col-3"></div>
				<div class="col-3 pull-9"></div>
			</div>
		</div>
		<div class="col-6">
			<div class="row">
				<div class="col-4 push-4"></div>
				<div class="col-4 pull-8"></div>
			</div>
		</div>
	</div>
</div>

<h3>Helper</h3>

<h4>Display Table</h4>

<div class="helper-display-table">
	<div>
		Cell Left<br/>
		with more than<br/>
		one line!
	</div>
	<div>
		Cell Right
	</div>
</div>
