<?php

$areas = get_field('fact_areas');
$profile = get_field('fact_profile');

?>

<td class="name"><?php the_title(); ?></td>
<td class="area area_wellness"><?= (in_array('wellness', $areas)) ? 'yes' : 'no' ?></td>
<td class="area area_sport"><?= (in_array('sport', $areas)) ? 'yes' : 'no' ?></td>
<td class="area area_med"><?= (in_array('med', $areas)) ? 'yes' : 'no' ?></td>
<td class="country"><? the_field('fact_country') ?></td>
<td class="profile"><? if ($profile) { ?><a href="<?= get_permalink($profile->ID) ?>">View Profile</a> <? } ?>
</td>