<?php

/**
 * Picturefill 1.2.1 Markup
 *
 * Image sizes must fo from small to large, when using min-width for media queries
 * The No-JS Fallback image is of the same size as the original image without picturefill was
 */

?>
<span data-picture data-alt="<?= $data->images_alt ?>" data-width="<?= $data->images_width ?>" id="<?= $data->images_id ?>" data-class="<?= $data->images_classes ?>">
	 <? foreach ($data->images as $name => $image): ?>
		 <span data-name="<?= $name ?>" data-src="<?= $image['source'] ?>" data-media="<?= $image['mq'] ?>"></span>
	 <? endforeach; ?>
	<noscript>
		<img name="<?= $data->images_name ?>" src="<?= $data->images_fallback[0] ?>" width="<?= $data->images_fallback[1] ?>" id="<?= $data->images_id ?>" class="<?= $data->images_classes ?>" alt="<?= $data->images_alt ?>">
	</noscript>
</span>