<table id="facts-table">
	<thead>
		<tr>
			<th data-sort="name" class="sort"><?= __('Name') ?></th>
			<th data-sort="contact" class="sort"><?= __('Contact') ?></th>
			<th data-sort="area-wellness" class="sort area"><?= __('Wellness') ?></th>
			<th data-sort="area-sport" class="sort area"><?= __('Sport') ?></th>
			<th data-sort="area-med" class="sort area"><?= __('Medical') ?></th>
			<th data-sort="address" class="sort address"><?= __('Address') ?></th>
			<th data-sort="country" class="sort"><?= __('Country') ?></th>
			<th data-sort="search" class="search"><input type="text" class="search" placeholder="<?= __('Search') ?>"></th>
		</tr>
	</thead>
	<tbody class="list">

	<?php

	$loop = new WP_Query(array('post_type' => 'icelab_facts', 'posts_per_page' => -1));

	while ($loop->have_posts()) : $loop->the_post();

		echo TcWp::module('Facts')->classes('base')->tag('tr')->in(2);

	endwhile;

	wp_reset_postdata();
	?>

	</tbody>
</table>
