<h2>Page not Found (404)</h2>
<p>Die gesuchte Seite konnte leider nicht gefunden werden.</p><br />
<h3>Bitte führen Sie einen der folgenden Schritte durch</h3>
<ul class="base">
	<li>Überprüfen Sie, ob Sie die Webadresse richtig eingegeben haben.</li>
    <li>Die Seite existert möglicherweise nicht mehr, aktualisieren Sie Ihre Favoriten.</li>
    <li>Klicken Sie auf "Back" in Ihrem Browser, oder gehen Sie <a href="<?= bloginfo('url') ?>">zurück zur Home Seite</a>.</li>
    <li>Suchen Sie nach der gewünschten Seite, die Suchfunktion befindet sich oben rechts.</li>
</ul>