
<?php

		//
		// Profile Link

		$profileLink = get_field('profile');
?>

	<td class="name"><?php the_title(); ?></td>
	<td class="contact"><? the_field('contact') ?></td>
	<td class="area area-wellness">x</td>
	<td class="area area-sport">x</td>
	<td class="area area-med">x</td>
	<td class="address"><? the_field('address') ?></td>
	<td class="country"><? the_field('country') ?></td>
	<td class="profile"><? if($profileLink) { ?><a href="<?= get_permalink($profileLink->ID) ?>">View Profile</a> <? } ?></td>