<div class="hd">
	<h1 class="title"><?php the_title(); ?></h1>
	<?php
	$attachment_id = get_field('profile-headerimage');
	$image = wp_get_attachment_image_src($attachment_id, 'theme-profile-header');
	?>
	<img src="<?= $image[0]; ?>" width="<?= $image[1]; ?>" height="<?= $image[2]; ?>"/>

</div>

<div class="bd base section">
	<div class="row">
		<div class="col-left">
			<?php
			$attachment_id = get_field('profile-logo');
			$image = wp_get_attachment_image_src($attachment_id, 'theme-profile-medium');
			?>
			<img src="<?= $image[0]; ?>" width="<?= $image[1]; ?>" height="<?= $image[2]; ?>"/>
		</div>
		<div class="col-right">
			<?php the_field('profile-description'); ?>
		</div>
	</div>
</div>

<div class="bd base section">
	<?php if(get_field('profile-offers')): ?>

		<h2>Offers</h2>

		<?php while(has_sub_field('profile-offers')): ?>

			<div class="row">

				<div class="col-left">

					<?php
					$attachment_id = get_sub_field('profile-offer-image');
					$image = wp_get_attachment_image_src($attachment_id, 'theme-profile-medium');
					?>

					<img src="<?= $image[0]; ?>" width="<?= $image[1]; ?>" height="<?= $image[2]; ?>"/>
				</div>

				<div class="col-right">
			 		<?php the_sub_field('profile-offer-description'); ?>
				</div>

			</div>
		<?php endwhile; ?>

	<?php endif; ?>

</div>
<div class="bd base section">

	<?php if(get_field('profile-media')): ?>

		<h2>Media</h2>

		<div class="row">

		<?php while(has_sub_field('profile-media')):

			if( get_sub_field('profile-media-file') ):

				$attachment_id = get_sub_field('profile-media-file');

				echo getMarkupFromAttachment($attachment_id, 'theme-profile-media');

			endif; ?>

		<?php endwhile; ?>

		</div>

	<?php endif; ?>

</div>