<div class="hd">
	<h1 class="title"><?php the_title(); ?></h1>
	<?php
	$attachment_id = get_field('profile_headerimage');
	$image = wp_get_attachment_image_src($attachment_id, 'theme-profile-header');
	?>
	<img src="<?= $image[0]; ?>" width="<?= $image[1]; ?>" height="<?= $image[2]; ?>"/>

</div>

<div class="bd base section">
	<div class="row">
		<div class="col-left">
			<?php
			$attachment_id = get_field('profile_logo');
			$image = wp_get_attachment_image_src($attachment_id, 'theme-profile-medium');
			?>
			<img src="<?= $image[0]; ?>" width="<?= $image[1]; ?>" height="<?= $image[2]; ?>"/>
		</div>

		<div class="col-right">
		<?php if (get_field('profile_description_en')): ?>
			<ul class="lang-switch-box">
				<li class="lang-switch-item active"><?= __('Description', 'awesome-textdomain') ?></li>
				<li class="lang-switch-item"><?= __('In English', 'awesome-textdomain') ?></li>
			</ul>
			<div class="desc-box">
				<div class="desc-item">
					<?= get_field('profile_description'); ?>
				</div>
				<div class="desc-item">
					<?php the_field('profile_description_en'); ?>
				</div>
			</div>
			<? else: ?>
				<?= get_field('profile_description'); ?>
			<? endif; ?>
		</div>
	</div>
</div>

<?php if(get_field('profile_offers')): ?>
	<div class="bd base section">

		<h2>Offers</h2>

		<?php while(has_sub_field('profile_offers')): ?>

			<div class="row">

				<div class="col-left">

					<?php
					$attachment_id = get_sub_field('profile_offer_image');
					$image = wp_get_attachment_image_src($attachment_id, 'theme-profile-medium');
					?>

					<img src="<?= $image[0]; ?>" width="<?= $image[1]; ?>" height="<?= $image[2]; ?>"/>
				</div>

				<div class="col-right">
			 		<?php the_sub_field('profile_offer_description'); ?>
				</div>

			</div>
		<?php endwhile; ?>

	</div>
<?php endif; ?>


<?php if(get_field('profile_media')): ?>
	<div class="bd richtext section">

		<h2>Media</h2>

		<div class="row">

		<?php while(has_sub_field('profile_media')):

			if( get_sub_field('profile_media_file') ):

				$attachment_id = get_sub_field('profile_media_file');

				echo getMarkupFromAttachment($attachment_id, 'theme-profile-media');

			endif; ?>

		<?php endwhile; ?>

		</div>

	</div>

<?php endif; ?>

<?php

	//
	// Get Facts for this Profile

	$facts = get_posts(array(
		'post_type' => 'facts',
		'meta_query' => array(
					array(
						'key' => 'fact_profile', // name of custom field
						'value' => get_the_ID(), // matches exaclty "123", not just 123. This prevents a match for "1234"
						'compare' => 'LIKE'
					)
				)
	));

	$factsWithCustom = enhanceGetPostsWithCustomFields($facts);

	if($factsWithCustom): ?>

		<div class="bd richtext section">

			<h2><?= __('Contact', 'awesome-textdomain') ?></h2>

			<?php

			foreach($factsWithCustom as $fact): ?>

				<?php

				$address = array();

				if($fact->fact_street !== false) {
					array_push($address, $fact->fact_street);
				}

				if($fact->fact_plz_city !== false) {
					array_push($address, $fact->fact_plz_city);
				}

				if($fact->fact_country !== false) {
					array_push($address, $fact->fact_country);
				}

				echo '<p>' . implode('<br/>', $address) . '</p>';

				?>

				<p><a target="_blank" href="http://maps.google.com/maps?saddr=%20&daddr=<?= implode('%20', $address) ?>"><?= __('Calculate Route with Google Maps', 'awesome-textdomain') ?></a></p>

				<?= module('map')->template('contact')->skin('contact')->data($fact)->attribs(array('role' => 'aside'))->data(array('fact' => $fact)); ?>

			<? endforeach; ?>


		</div>

<?php endif; ?>