<?php

global $wp_query;
$results = $wp_query->found_posts;
$s_query = get_search_query();

?>

	<div class="content-meta">
		<?= TcWp::module('Filter')->template('search')->params(array('results' => $results, 'query' => $s_query)); ?>
	</div>

	<?php /* Start the Loop */ ?>
	<?php while (have_posts()) : the_post(); ?>
		<?php /* Start the Loop */ ?>

		<?php global $post; ?>
		<?php if ($post->post_type == "post") : ?>

			<?= TcWp::module('ArticleTeaser') ?>

		<?php endif; ?>

	<?php endwhile; ?>


<!--			--><? //= TcWp::module('ArticleTeaserList')->in(2) ?>
<!--			--><? //= TcWp::module('ShowMore') ?>

</div>