<div class="grid-3 grid-mobile-12 grid-ipad-landscape-12 hide-print">Logo</div>
		<div class="grid-5 grid-mobile-12 grid-ipad-landscape-12 hide-print">Search</div>
		<div class="grid-4 grid-mobile-12 hide-ipad-landscape hide-mobile hide-print">Login</div>

		<div class="grid-12 hide-print debug-color-1">Primary navigation</div>


		<div class="grid-12 parent">

			<div class="grid-8 grid-tablet-12 grid-mobile-12 float-right debug-color-3">
				<div class="content" style="height:242px;">
					Slideshow content
				</div>
			</div>

			<div class="grid-4 grid-tablet-4 grid-mobile-12 debug-color-2">
				<div class="content" style="height:30px;">
					Slideshow menu 1
				</div>
			</div>
			<div class="grid-4 grid-tablet-4 grid-mobile-12 debug-color-2">
				<div class="content" style="height:30px;">
					Slideshow menu 2
				</div>
			</div>
			<div class="grid-4 grid-tablet-4 grid-mobile-12 debug-color-2">
				<div class="content" style="height:30px;">
					Slideshow menu 3
				</div>
			</div>

		</div>

		<div class="grid-12 debug-color-1">Breadcrumb</div>

		<div class="grid-4 grid-ipad-landscape-6 grid-tablet-6 grid-mobile-12 push-tablet-6">
			<div class="content" style="height:100px;">
				Highlight 1
			</div>
		</div>
		
		<div class="grid-4 grid-ipad-landscape-6 grid-tablet-6 grid-mobile-12 pull-tablet-6">
			<div class="content" style="height:100px;">
				Highlight 2
			</div>
		</div>
		<div class="grid-4 grid-ipad-landscape-12 grid-tablet-12 grid-mobile-12 grid-tablet-clear">
			<div class="content" style="height:100px;">
				Highlight 3
			</div>
		</div>

		<div class="grid-6 grid-mobile-12 debug-color-3">
			<div class="content" style="height:100px">
				Custom box 1
			</div>
		</div>
		<div class="grid-6 grid-mobile-12 debug-color-3">
			<div class="content" style="height:100px">
				Custom box 2
			</div>
		</div>

		<div class="grid-12 hide-print">Footer</div>