<?php

//
// Get Facts

$posts = get_posts(array(
	'post_type'		=> 'icelab_facts',
	'posts_per_page'	=> -1
));

$postsWithCustom = enhancePostsWithCustomFields($posts);

?>

<script type="text/javascript">

	<?= "var modMapIcelabFacts=". json_encode($postsWithCustom); ?>

</script>

<div id="map-canvas" style="width: 100%; height: 400px"></div>

<ul class="filter-list">
	<li>Filter:</li>
	<li><label for="wellness" class="filter-item" data-filter="wellness" /><input id="wellness" type="checkbox" value="wellness" checked>Wellness</input></li>
	<li><label for="sport" class="filter-item" data-filter="sport" /><input id="sport" type="checkbox" value="sport" checked>Sport</li>
	<li><label for="medical" class="filter-item" data-filter="medical"/><input id="medical" type="checkbox" value="medical" checked>Medical</li>
</ul>
