<div id="map-canvas" style="width: 100%; height: 300px"></div>

<?php

//
// Get Facts

//	$arrPois = Array();
$query = new WP_Query(array('post_type' => 'icelab_facts', 'posts_per_page' => -1));

//	while ($loop->have_posts()) : $loop->the_post();

//		 Get Type
//		$type = strtolower(join('-', get_field('fact_areas')));

//		 Content
//		$title = '<h2>' . get_the_title() . '</h2>';
//		$body = '<div class="row"><label>' . __('Areas') . '</label>' . join(', ', get_field('fact_areas')). '</div><div class="row"><label>' . __('Address') . '</label>' . get_field('fact_street') . '<br/>' . get_field('fact_plz_city') . '<br/>' . get_field('fact_country') .  '</div><div class="row"><a class="profile-link" href="' . get_permalink() . '">' . __('View the full Profile') . '</a></div>';

//		 Poi
//		$arrPois[] = new Mappress_Poi(array('title' => $title, 'body' => $body, "address" => get_field('fact_street') . ' ' . get_field('fact_plz_city') . ' ' . get_field('fact_country')));
//		$arrPois[count($arrPois) - 1]->geocode();

//	endwhile;

	wp_reset_postdata();

//	$mymap->pois = $arrPois;


// Display map

//	echo $mymap->display();
//
//	if ($children = get_children('post_type=page&numberposts=1')) {
//    	$first_child = $children[0];
//    	$first_child_permalink = get_permalink($first_child->ID);
//    	$listAllIcelabsLink = $first_child_permalink;
//  	}
//?>




<ul class="legend-list">
	<li><label for="wellness"/><input id="wellness" type="checkbox">Wellness</input></li>
	<li><label for="sport"/><input id="sport" type="checkbox">Sport</li>
	<li><label for="medical"/><input id="medical" type="checkbox">Medical</li>
	<?php
	wp_list_pages(
		array(
			'child_of' => get_the_ID(),
			'depth' => 1,
			'title_li' => ''
		)
	);
	?>
</ul>

