<?php

//
// Get Facts

$posts = get_posts(array(
	'post_type'		=> 'icelab_facts',
	'posts_per_page'	=> -1
));

$postsWithCustom = enhanceGetPostsWithCustomFields($posts);

?>

<script type="text/javascript">

	<?= "var modMapIcelabFacts=". json_encode($postsWithCustom); ?>

</script>

<ul class="filter-list">
	<li class="filter-item"><label for="wellness" class="filter-label" data-filter="wellness" /><input id="wellness" type="checkbox" value="wellness" checked>Wellness</input></li>
	<li class="filter-item"><label for="sport" class="filter-label" data-filter="sport" /><input id="sport" type="checkbox" value="sport" checked>Sport</li>
	<li class="filter-item"><label for="medical" class="filter-label" data-filter="medical"/><input id="medical" type="checkbox" value="medical" checked>Medical</li>
</ul>

<div class="map-canvas"></div>