<?php

	$mymap = new Mappress_Map(array('height' => 200));
	$arrPois = Array();

	// Popover Content
	$title = '<h2>' . $data->post_title . '</h2>';
	$body = '<div class="row"><label>' . __('Contact') . '</label>' .  get_field('contact', $data->ID) . '</div><div class="row"><label>' . __('Areas') . '</label>' . join(', ', get_field('areas_of_application', $data->ID)). '</div><div class="row"><label>' . __('Address') . '</label>' . get_field('address', $data->ID) . '</div></div>';

	// POI
	$arrPois[] = new Mappress_Poi(array('title' => $title, 'body' => $body, "iconid" => $type.'.png', "address" => get_field('address', $data->ID)));

	$arrPois[count($arrPois) - 1]->geocode();


	$mymap->pois = $arrPois;

	echo $mymap->display();

?>
