<?php

	$mymap = new Mappress_Map(array('height' => 500));
	$arrPois = Array();

	$loop = new WP_Query(array('post_type' => 'icelab_facts', 'posts_per_page' => -1));

	while ($loop->have_posts()) : $loop->the_post();

		//
		// Get Type
		$type = strtolower(join('-', get_field('areas_of_application')));

		//
		// Content
		$title = '<h2>' . get_the_title() . '</h2>';
		$body = '<div class="row"><label>' . __('Contact') . '</label>' .  get_field('contact') . '</div><div class="row"><label>' . __('Areas') . '</label>' . join(', ', get_field('areas_of_application')). '</div><div class="row"><label>' . __('Address') . '</label>' . get_field('address') . '</div><div class="row"><a class="profile-link" href="' . get_permalink() . '">' . __('View the full Profile') . '</a></div>';

		$arrPois[] = new Mappress_Poi(array('title' => $title, 'body' => $body, "iconid" => $type.'.png', "address" => get_field('address')));

		$arrPois[count($arrPois) - 1]->geocode();

	endwhile;

	wp_reset_postdata();

	$mymap->pois = $arrPois;

	echo $mymap->display();



if ($children = get_children('post_type=page&numberposts=1')) {
      $first_child = $children[0];
      $first_child_permalink = get_permalink($first_child->ID);
      $listAllIcelabsLink = $first_child_permalink;
  }
?>

<ul class="legend-list">
	<li><a class="wellness" href="">Wellness</a></li>
	<li><a class="sport" href="">Sport</a></li>
	<li><a class="med" href="">Medical</a></li>
	<?php
		wp_list_pages(
				array(
						'child_of' => get_the_ID(),
						'depth' => 1,
						'title_li' => ''
				)
		);
	?>
</ul>

